### ISSUE TITLE
How do I get him up and running?

### ISSUE THREAD

**Issue by wum0** [CMatri/MeetC2#1]
I have done the following：
```
git clone https://github.com/CMatri/MeetC2.git
cd MeetC2 
go build .
./c2
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.getIfaceIp(0x73bfc8, 0xb, 0x30, 0x28)
	/home/***/****/MeetC2/server.go:82 +0xe5
main.HttpListener.startListener(0x73bfc8, 0xb, 0x73bfb2, 0xb, 0x1f40, 0x4687e5, 0xc000000180)
	/home/***/****/MeetC2/httplistener.go:39 +0x95
main.main()
	/home/****/****/MeetC2/server.go:629 +0x10b
```

**Comment by iammaguire** [comment]
The HttpListener is instantiated with the first two command line arguments - the first being the interface you would like to listen on and the second being the hostname.  I'll add that to the doc! Oversight on my part. 

If you want to listen on wlp2s0 with command.com being the hostname you would run 
`./c2 wlp2s0 command.com`

I was surprised when I came back here and saw it had gained a following. Had it public mostly so my colleagues could peruse the code. Now that there's a growing interest I'll put an effort into revising the docs once I'm done with the certification I'm currently taking. Thank you for your interest

**Comment by wum0** [comment]
```
ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
 *****
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
 ****

hostname
kali

./c2 eth0 kali         
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.getIfaceIp(0x73bfc8, 0xb, 0x30, 0x28)
	/home/***/MeetC2/server.go:82 +0xe5
main.HttpListener.startListener(0x73bfc8, 0xb, 0x73bfb2, 0xb, 0x1f40, 0x4687e5, 0xc000000180)
	/home/***/MeetC2/httplistener.go:39 +0x95
main.main()
	/home/***/MeetC2/server.go:629 +0x10b

```

I still encounter this error.
Maybe you should be outputting some error messages  (¬‿¬)

**Comment by iammaguire** [comment]
eth0 wouldn't have an IP associated with it, only a MAC address. Currently this project only supports wireless connections. Wired connections would be a good feature to add though, I've put it on the list. Try it out over a wireless interface. 
Better debugging messages are added to the list as well. As I said I didn't expect the interest as it was only a hobby project until now.

**Comment by wum0** [comment]
Looking forward to the subsequent updates
